/**
 * HTTP path constants — aligned with instollar-webappV2/docs/API_ENDPOINTS.md
 * Paths are relative; prefix with the correct service base via apiUrl().
 */

export const refreshTokenEndpoint = '/auth/refresh';
export const logoutEndpoint = '/auth/logout';

export const authPaths = {
  register: '/user/register',
  confirmOtp: '/user/confirm-otp',
  login: '/user/login',
  sendOtp: '/user/send-otp',
  changePassword: '/user/change-password',
  health: '/user/health',
  twoFaLoginVerify: '/auth/2fa/login-verify',
  twoFaEnable: '/auth/2fa/enable',
  twoFaDisable: '/auth/2fa/disable',
  twoFaVerifySetup: (otp: string) => `/auth/2fa/verify-setup?otp=${encodeURIComponent(otp)}`,
  guarantorForm: '/installer/guarantor-form',
} as const;

export const sharedPaths = {
  uploadFile: '/file/upload',
  chatInbox: '/chat/inbox',
  chatHistoryDirect: (threadId: string) => `/chat/history/direct/${threadId}`,
  chatHistoryOtherUser: (otherUserId: string) => `/chat/history/other-user/${otherUserId}`,
  chatMarkRead: (convoId: string, isRead: boolean) => `/chat/status/${convoId}?isRead=${isRead}`,
  chatMarkAllRead: (isRead: boolean) => `/chat/status/all?isRead=${isRead}`,
  chatHistoryStep: '/chat/history/step',
} as const;

export const userPaths = {
  getAll: '/user/get-all',
  getAllCompanyUsers: '/user/get-all-company-users',
  create: '/user/create',
  update: (id: string) => `/user/update/${id}`,
  delete: (id: string) => `/user/delete/${id}`,
} as const;

export const basePaths = {
  companyUpdate: '/company/update',
  companyDashboard: '/company/dashboard',
  projectLocationReport: (projectId: string) => `/projects/cluster/${projectId}/location-report`,
  projectReport: (projectId: string) => `/project-report/${projectId}`,
  qaDashboard: '/admin/qa/dashboard',
  qaProjects: '/admin/qa/projects',
  qaProjectSingle: (id: string) => `/admin/qa/projects/${id}`,
  storeFrontOverview: '/store-front/overview',
  storeFrontOrders: '/store-front/orders',
  storeFrontProducts: '/store-front/products',
  storeFrontProduct: (id: string) => `/store-front/products/${id}`,
  installerStoreFrontOverview: '/installer/storefront/overview',
  installerStoreFrontInterests: '/installer/storefront/interests',
  installerStoreFrontProducts: '/installer/storefront/products',
  installerSettings: '/installer/settings',
} as const;

export const adminPaths = {
  stats: '/admin/stats',
  profile: '/admin/profile',
  updateProfile: '/admin/update-profile',
  dashboardMetrics: '/dashboard/metrics',
  dashboardOverview: '/dashboard/overview',
  dashboardPayoutDistribution: '/dashboard/payout-distribution',
  dashboardDemographics: '/dashboard/demographics',
  dashboardRegistrations: '/dashboard/registrations',
  dashboardLocations: '/dashboard/locations',
  dashboardCompanyJobs: '/dashboard/company-jobs',
  dashboardInstallerJobRate: '/dashboard/installer-job-rate',
  dashboardGenerateReport: '/dashboard/generate-report',
  getUsers: userPaths.getAll,
  getAllCompanyUsers: userPaths.getAllCompanyUsers,
  createUser: userPaths.create,
  updateUser: userPaths.update,
  deleteUser: userPaths.delete,
  crmEndUsers: '/crm/end-users',
  crmCompleteProfileReminder: (userId: string, userType: string) =>
    `/crm/complete-profile-reminder/${userId}/${userType}`,
  getOnboardedAdmins: '/admin/get-onboarded-admins',
  getOnboardedCompanies: '/admin/get-onboarded-companies',
  assignAdminToCompany: '/admin/assign-admin-to-company',
  permissions: '/admin/get-all-permissions',
  rolesGetAll: '/role/get-all',
  roleSingle: (id: string) => `/role/single/${id}`,
  roleCreate: '/role/create',
  roleUpdate: (id: string) => `/role/update/${id}`,
  roleDelete: (id: string) => `/role/delete/${id}`,
  jobRequestsGetAll: '/admin/job-requests/get-all',
  jobRequestSingle: (id: string) => `/admin/job-requests/single/${id}`,
  markJobComplete: (id: string) => `/admin/job-requests/mark-complete/${id}`,
  updateInstallationDate: (id: string) => `/admin/job-requests/update-installation-date/${id}`,
  cancelJobRequest: (id: string) => `/admin/job-requests/cancel/${id}`,
  jobRequestRate: (jobRequestId: string, raterType: string) =>
    `/admin/job-requests/${jobRequestId}/rate?raterType=${encodeURIComponent(raterType)}`,
  swapWorkflow: (jobRequestId: string) => `/assign-installer/${jobRequestId}/workflows/swap`,
  searchInstallers: '/assign-installer/search',
  assignInstaller: (jobRequestId: string) => `/assign-installer/assign/${jobRequestId}`,
  unassignWorkflow: (jobRequestId: string) => `/assign-installer/workflow/${jobRequestId}`,
  installerProfile: (installerId: string) => `/assign-installer/installer-profile/${installerId}`,
  verifyOnProfile: '/installer/profile',
  getUserProfile: (id: string) => `/crm/get-user/${id}`,
  updateInstaller: (id: string) => `/crm/update-installer/${id}`,
  updateCompany: (id: string) => `/crm/update-company/${id}`,
  userJobs: (id: string, userType: string) => `/crm/user-jobs/${id}/${userType}`,
  workflowsGetAll: '/workflows/get-all',
  workflowSingle: (id: string) => `/workflows/single/${id}`,
  workflowCreate: '/workflows/create',
  workflowUpdate: (id: string) => `/workflows/update/${id}`,
  workflowsByCompany: (companyId: string) => `/workflows/company/${companyId}`,
  workflowDuplicate: (id: string) => `/workflows/duplicate/${id}`,
  workflowDelete: (id: string) => `/workflows/delete/${id}`,
  workflowStepChats: (stepId: string) => `/workflows/step-chats/${stepId}`,
  financeOverview: '/admin/finance/overview',
  financeTransactions: '/admin/finance/transactions',
  financeReportsGenerate: '/admin/finance/reports/generate',
  financeInstallerWallets: '/admin/finance/installer-wallets',
  financeUnpaidProjects: (installerId: string) =>
    `/admin/finance/installer/${installerId}/view_unpaid_projects`,
  financeUnpaidInstallers: '/admin/finance/unpaid-installers',
  financeUnpaidExport: '/admin/finance/installers/unpaid/export',
  financePayoutPreview: '/admin/finance/installers/payout/preview',
  financePayoutConfirm: '/admin/finance/installers/payout/confirm',
  financeCompanies: '/admin/finance/companies',
  financeCompanyTransactions: (companyId: string) =>
    `/admin/finance/companies/${companyId}/transactions`,
  financeCompanyBillingSummary: (companyId: string) =>
    `/admin/finance/companies/${companyId}/billing_summary`,
  financeCompaniesOverview: '/admin/finance/companies/overview',
  financePaymentReminder: '/admin/finance/companies/payment-reminder',
  financeConfigPaymentGateway: '/admin/finance/config/payment-gateway',
  financeConfigMasterAccount: '/admin/finance/config/master-account',
  financeConfigPinSet: '/admin/finance/config/pin/set',
  financeConfigPinUpdate: '/admin/finance/config/pin/update',
  financeConfigPinStatus: '/admin/finance/config/pin/status',
  financeAuditTrail: '/admin/finance/audit-trail',
  financeInstallerProjects: (installerId: string) =>
    `/admin/finance/installers/${installerId}/projects`,
  meshGridGetAll: '/mesh-grid/get-all',
  meshGridSingle: (id: string) => `/mesh-grid/single/${id}`,
  meshGridAssignWorkflows: (id: string) => `/mesh-grid/assign-workflows/${id}`,
  meshGridAssign: (id: string) => `/mesh-grid/assign/${id}`,
  meshGridReports: (jobId: string) => `/mesh-grid/reports/${jobId}`,
  meshGridReportWorkflow: (jobId: string, workflowId: string) =>
    `/mesh-grid/report-workflows/${jobId}/${workflowId}`,
  meshGridUpdateReport: (reportId: string) => `/mesh-grid/update-report/${reportId}`,
  miniGridGetAll: '/mini-grid/get-all',
  miniGridSingle: (id: string) => `/mini-grid/single/${id}`,
  miniGridCompanyInstallers: (companyId: string) =>
    `/mini-grid/get-all-installers/${companyId}`,
  miniGridAssignInstallersToCompany: '/mini-grid/assign-installer-to-company',
  miniGridUnassignInstallersFromCompany: '/mini-grid/unassign-installer-to-company',
  commercialAuditById: (auditId: string) => `/site-audit/commercial-audit/${auditId}`,
  commercialAuditByJob: (jobRequestId: string) =>
    `/site-audit/commercial-job/${jobRequestId}`,
  residentialAuditById: (auditId: string) => `/site-audit/residential-audit/${auditId}`,
  residentialAuditByJob: (jobRequestId: string) =>
    `/site-audit/residential-job/${jobRequestId}`,
  updateCommercialAudit: (auditId: string) => `/site-audit/update-commercial/${auditId}`,
  updateResidentialAudit: (auditId: string) => `/site-audit/update-residential/${auditId}`,
  invoiceCreate: (jobRequestId: string) => `/invoices/${jobRequestId}/create`,
  invoiceSend: (invoiceId: string) => `/invoices/${invoiceId}/send`,
  invoicesGetAll: '/invoices/get-all',
  invoiceUpdate: (invoiceId: string) => `/invoices/${invoiceId}/update`,
  invoiceById: (invoiceId: string) => `/invoices/id/${invoiceId}`,
  invoiceByJobRequest: (jobRequestId: string) => `/invoices/job-request/${jobRequestId}`,
  invoiceSettings: '/admin/invoice-settings',
  invoiceDelete: (invoiceId: string) => `/invoices/${invoiceId}/delete`,
  pricingSeed: '/pricing-calculator/seed',
  pricingItems: '/pricing-calculator/items',
  pricingItemUpdate: (id: string) => `/pricing-calculator/items/${id}`,
  pricingCalculate: '/pricing-calculator/calculate',
  badgeCreate: '/badges/create',
  badgesGetAll: '/badges/get-all',
  installerBadges: (installerId: string) => `/admin/badges/${installerId}`,
  badgeUpdate: (id: string) => `/badges/${id}`,
  badgeToggleStatus: (id: string) => `/badges/${id}/status`,
  badgeAssign: '/admin/badges/assign',
  badgeUnassign: (installerId: string, badgeId: string) =>
    `/admin/badges/unassign/${installerId}/${badgeId}`,
  badgeAutoAssignByCompany: (companyId: string) =>
    `/admin/badges/auto-assign/company/${companyId}`,
  badgeDelete: (id: string) => `/badges/${id}`,
  questionsGetAll: '/question-bank/get-all',
  questionSingle: (id: string) => `/question-bank/single/${id}`,
  questionsCreate: '/question-bank/create',
  questionUpdate: (id: string) => `/question-bank/update/${id}`,
  questionDelete: (id: string) => `/question-bank/delete/${id}`,
  languageCreate: '/language/create',
  languagesGetAll: '/language/get-all',
  languageSingle: (id: string) => `/language/get/${id}`,
  languageUpdate: (id: string) => `/language/update/${id}`,
  languageDelete: (id: string) => `/language/delete/${id}`,
  metadataCreate: '/metadata',
  metadataGetAll: '/metadata',
  metadataByType: (type: string) => `/metadata/${type}`,
  metadataToggle: (id: string) => `/metadata/${id}/toggle`,
  metadataDelete: (id: string) => `/metadata/${id}`,
  adPackageCreate: '/admin/ad-packages/create',
  adPackagesGetAll: '/admin/ad-packages',
  adPackageSingle: (id: string) => `/admin/ad-packages/${id}`,
  adPackageToggleStatus: (id: string) => `/admin/ad-packages/${id}/toggle-status`,
  configurationsGetAll: '/admin/get-all-configurations',
  configurationEdit: (configId: string) => `/admin/edit-config/${configId}`,
  auditLogsGetAll: '/audit-logs/get-all',
  toolboxTemplateCreate: '/toolbox/templates',
  toolboxTemplateUpdate: (templateId: string) => `/toolbox/templates/${templateId}`,
  toolboxTemplatesGetAll: '/toolbox/templates',
  toolboxAssignTemplate: (jobId: string, templateId: string) =>
    `/toolbox/jobs/${jobId}/assign/${templateId}`,
  toolboxJobSubmissions: (jobId: string) => `/toolbox/jobs/${jobId}/submissions`,
  toolboxSubmission: (submissionId: string) => `/toolbox/submissions/${submissionId}`,
  toolboxTemplateDelete: (templateId: string) => `/toolbox/templates/${templateId}`,
  notifications: '/admin/notifications',
  notificationRead: (id: string) => `/admin/notifications/${id}/read`,
} as const;

export const companyPaths = {
  profile: '/company/profile',
  updateUser: '/company/update-user',
  update: '/company/update',
  dashboardOverview: '/dashboard/overview',
  notifications: '/company/notifications',
  notificationRead: (id: string) => `/company/notifications/${id}/read`,
  jobRequestsGetAll: '/job-request/get-all',
  jobRequestSingle: (requestId: string) => `/job-request/get-single/${requestId}`,
  jobRequestCreate: '/job-request/create',
  jobRequestCompleteCancel: (id: string, status: string) =>
    `/job-request/complete-cancel/${id}/${status}`,
  jobRequestApprove: (requestId: string) => `/job-request/approve/${requestId}`,
  rolePermissions: '/role/get-all-permissions',
  rolesGetAll: '/role/get-all',
  roleCreate: '/role/create',
  roleUpdate: (id: string) => `/role/update/${id}`,
  roleDelete: (id: string) => `/role/delete/${id}`,
  miniGridGetAllInstallers: '/mini-grid/get-all-installers',
  miniGridGetAll: '/mini-grid/get-all',
  miniGridSingle: (jobId: string) => `/mini-grid/single/${jobId}`,
  miniGridCreate: '/mini-grid/create',
  miniGridDelete: (id: string) => `/mini-grid/delete/${id}`,
  clusterGetAll: '/job-requests/cluster',
  clusterCreate: '/job-requests/cluster',
  projectWorkflowReports: (projectId: string) => `/workflows/reports/${projectId}`,
  submitInstallerRating: '/ratings/installer',
  workflowsGetAll: '/workflows/get-all',
  workflowSingle: (workflowId: string) => `/workflows/single/${workflowId}`,
  workflowCreate: '/workflows/create',
  workflowUpdate: (workflowId: string) => `/workflows/update/${workflowId}`,
  financeOverview: '/company/finance/overview',
  financeTransactions: '/company/finance/transactions',
  financeBillingSummary: '/company/finance/billing-summary',
  financeProjectInvoices: (projectId: string) =>
    `/company/finance/projects/${projectId}/invoices`,
  financeBanks: '/company/finance/banks',
  financeResolveAccount: '/company/finance/resolve-account',
  financeLinkBankAccount: '/company/finance/bank-account',
  financeInitializePayment: '/company/finance/invoices/initialize-payment',
  financePaymentPreview: (companyId: string) => `/company/finance/${companyId}/payment/preview`,
  financePaymentConfirm: (companyId: string) => `/company/finance/${companyId}/payment/confirm`,
  invoiceById: (invoiceId: string) => `/company/invoices/id/${invoiceId}`,
  invoicePay: (invoiceId: string) => `/company/invoices/${invoiceId}/pay`,
  notificationsBase: '/notifications',
  meshGridGetAll: '/mesh-grid/get-all',
  meshGridSingle: (id: string) => `/mesh-grid/get-single/${id}`,
  meshGridCreate: '/mesh-grid/create',
  meshGridUpdate: (id: string) => `/mesh-grid/update/${id}`,
  meshGridDelete: (id: string) => `/mesh-grid/delete/${id}`,
  reportLocations: (jobId: string) => `/reports/${jobId}/locations`,
  reportLocationCommunities: (locationId: string) =>
    `/reports/locations/${locationId}/communities`,
  reportCommunityDailyReports: (communityId: string) =>
    `/reports/communities/${communityId}/daily-reports`,
  reportTechnicalDetails: (reportId: string) => `/reports/technical-details/${reportId}`,
  reportContents: (jobId: string, reportId: string) =>
    `/reports/contents/${jobId}/${reportId}`,
} as const;

export const installerPaths = {
  profile: '/installer/profile',
  update: '/installer/update',
  myRating: '/installer/my-rating',
  toggleAvailability: '/installer/toggle-availability',
  settings: '/installer/settings',
  languages: '/installer/languages',
  products: '/installer/products',
  badges: '/installer/badges',
  dashboardOverview: '/dashboard/overview',
  notifications: '/installer/notifications',
  notificationRead: (id: string) => `/installer/notifications/${id}/read`,
  jobRequestsGetAll: '/job-request/get-all',
  jobRequestView: (id: string) => `/job-request/view/${id}`,
  jobRequestAcceptReject: (id: string) => `/job-request/accept-reject-job/${id}`,
  jobRequestUpdateBoq: (id: string) => `/job-request/update-boq/${id}`,
  jobRequestUpdateItems: (jobId: string) => `/job-request/update-item/${jobId}`,
  commercialSiteAuditByJob: (jobRequestId: string) =>
    `/site-audit/get-by-job/${jobRequestId}`,
  commercialSiteAuditSubmit: '/site-audit/submit',
  commercialSiteAuditUpdate: (auditId: string) => `/site-audit/update/${auditId}`,
  residentialSiteAuditByJob: (jobRequestId: string) =>
    `/residential-site-audit/get-by-job/${jobRequestId}`,
  residentialSiteAuditSubmit: '/residential-site-audit/submit',
  residentialSiteAuditUpdate: (auditId: string) =>
    `/residential-site-audit/update/${auditId}`,
  miniGridGetAll: '/mini-grid/get-all',
  miniGridSingle: (jobId: string) => `/mini-grid/single/${jobId}`,
  meshGridGetAll: '/mesh-grid/get-all',
  meshGridSingle: (id: string) => `/mesh-grid/single/${id}`,
  meshGridReportCreate: '/reports/create',
  meshGridReportCreateNew: '/reports/create-new',
  meshGridReportStepCreate: '/reports/report-step/create',
  meshGridReportStepUpdate: (id: string) => `/reports/report-step/update/${id}`,
  meshGridPersonalSummary: (jobId: string) => `/reports/personal-summary/${jobId}`,
  meshGridProjectActivity: (jobId: string) => `/reports/project-activity/${jobId}`,
  meshGridReportCommission: (reportId: string) => `/reports/commission/${reportId}`,
  meshGridOfflineGenerateSlots: '/reports/offline/generate-slots',
  meshGridOfflineSync: '/reports/offline/sync',
  toolboxActiveTemplates: (jobId: string) => `/toolbox/jobs/${jobId}/active-templates`,
  toolboxSubmitBrief: (jobId: string) => `/toolbox/jobs/${jobId}/submit`,
  toolboxMySubmissions: (jobId: string) => `/toolbox/jobs/${jobId}/my-submissions`,
  workflowGetAll: (projectId: string) => `/workflow/get-all/${projectId}`,
  workflowSingle: (projectId: string, workflowId: string) =>
    `/workflow/single/${projectId}/${workflowId}`,
  workflowSubmit: (jobId: string) => `/workflow-content/submit/${jobId}`,
  workflowContentDelete: (contentId: string) => `/workflow-content/${contentId}`,
  workflowStepChats: (stepId: string) => `/workflow/step-chats/${stepId}`,
  workflowsStepChats: (stepId: string) => `/workflows/step-chats/${stepId}`,
  jobRequestAcceptPrecautions: (requestId: string) =>
    `/job-request/accept-precautions/${requestId}`,
  financeWallet: '/installer/finance/wallet',
  financeWalletStats: '/installer/finance/wallet/stats',
  financeHmoContributions: '/installer/finance/hmo/contributions',
  financeWalletCreatePin: '/installer/finance/wallet/create-pin',
  financeWalletCreate: '/installer/finance/wallet/create',
  financeWalletVerifyId: '/installer/finance/wallet/verify-id',
  financeBanks: '/installer/finance/banks',
  financeWalletLinkBank: '/installer/finance/wallet/link-bank',
  financeWalletResolveAccount: '/installer/finance/wallet/resolve-account',
  financeWalletBankAccounts: '/installer/finance/wallet/bank-accounts',
  financeWalletBankAccount: (bankAccountId: string) =>
    `/installer/finance/wallet/bank-account/${bankAccountId}`,
  financeInitiateWithdrawal: '/installer/finance/initiate/withdrawal',
  financeConfirmWithdrawal: '/installer/finance/confirm/withdrawal',
  financePension: '/installer/finance/pension',
  financePensionContributions: '/installer/finance/pension/contributions',
  financePensionContactProvider: '/installer/finance/pension/contact-provider',
  financePensionLink: '/installer/finance/pension/link',
  financePensionEnroll: '/installer/finance/pension/enroll',
  financeHmo: '/installer/finance/hmo',
  financeHmoLink: '/installer/finance/hmo/link',
  financeHmoEnroll: '/installer/finance/hmo/enroll',
  financeHmoContactProvider: '/installer/finance/hmo/contact-provider',
  financeWalletTransactions: '/installer/finance/wallet/transactions',
  assessmentGetAll: '/assessment/get-all',
  assessmentStart: '/assessment/start',
  assessmentSubmit: '/assessment/submit',
  guarantorForm: '/installer/guarantor-form',
  esgInstallerDashboard: '/esg/installer-esg-dashboard',
  esgProject: (jobRequestId: string) => `/esg/project/${jobRequestId}`,
} as const;
